/**
 * ISO-3166 alpha-2 + E.164 calling code + Persian/English name, one row per
 * dialable country/territory. Sourced from the mledoze/countries dataset
 * (https://github.com/mledoze/countries, MIT) and reduced to just the
 * fields the phone country-picker needs. Sorted by Persian name.
 *
 * Countries that share a calling code across a numbering plan (e.g. +1 for
 * both US and Canada) keep just the root code, not one of their area-code
 * suffixes — matching how people actually expect to search/dial.
 */
export interface Country {
  iso2: string
  dialCode: string
  nameFa: string
  nameEn: string
}

export const countries: Country[] = [
  { iso2: 'AW', dialCode: '+297', nameFa: 'آروبا', nameEn: 'Aruba' },
  { iso2: 'AR', dialCode: '+54', nameFa: 'آرژانتین', nameEn: 'Argentina' },
  { iso2: 'ZA', dialCode: '+27', nameFa: 'آفریقای جنوبی', nameEn: 'South Africa' },
  { iso2: 'AL', dialCode: '+355', nameFa: 'آلبانی', nameEn: 'Albania' },
  { iso2: 'DE', dialCode: '+49', nameFa: 'آلمان', nameEn: 'Germany' },
  { iso2: 'AG', dialCode: '+1268', nameFa: 'آنتیگوا و باربودا', nameEn: 'Antigua and Barbuda' },
  { iso2: 'AD', dialCode: '+376', nameFa: 'آندورا', nameEn: 'Andorra' },
  { iso2: 'AO', dialCode: '+244', nameFa: 'آنگولا', nameEn: 'Angola' },
  { iso2: 'AI', dialCode: '+1264', nameFa: 'آنگویلا', nameEn: 'Anguilla' },
  { iso2: 'KM', dialCode: '+269', nameFa: 'اتحاد قُمُر', nameEn: 'Comoros' },
  { iso2: 'AT', dialCode: '+43', nameFa: 'اتریش', nameEn: 'Austria' },
  { iso2: 'JO', dialCode: '+962', nameFa: 'اردن', nameEn: 'Jordan' },
  { iso2: 'AM', dialCode: '+374', nameFa: 'ارمنستان', nameEn: 'Armenia' },
  { iso2: 'UY', dialCode: '+598', nameFa: 'اروگوئه', nameEn: 'Uruguay' },
  { iso2: 'ER', dialCode: '+291', nameFa: 'اریتره', nameEn: 'Eritrea' },
  { iso2: 'UZ', dialCode: '+998', nameFa: 'ازبکستان', nameEn: 'Uzbekistan' },
  { iso2: 'AU', dialCode: '+61', nameFa: 'استرالیا', nameEn: 'Australia' },
  { iso2: 'SI', dialCode: '+386', nameFa: 'اسلوونی', nameEn: 'Slovenia' },
  { iso2: 'SZ', dialCode: '+268', nameFa: 'اسواتینی', nameEn: 'Eswatini' },
  { iso2: 'ES', dialCode: '+34', nameFa: 'اسپانیا', nameEn: 'Spain' },
  { iso2: 'AF', dialCode: '+93', nameFa: 'افغانستان', nameEn: 'Afghanistan' },
  { iso2: 'DZ', dialCode: '+213', nameFa: 'الجزایر', nameEn: 'Algeria' },
  { iso2: 'SV', dialCode: '+503', nameFa: 'السالوادور', nameEn: 'El Salvador' },
  { iso2: 'AE', dialCode: '+971', nameFa: 'امارات', nameEn: 'United Arab Emirates' },
  { iso2: 'ID', dialCode: '+62', nameFa: 'اندونزی', nameEn: 'Indonesia' },
  { iso2: 'GB', dialCode: '+44', nameFa: 'انگلیس', nameEn: 'United Kingdom' },
  { iso2: 'UA', dialCode: '+380', nameFa: 'اوکراین', nameEn: 'Ukraine' },
  { iso2: 'UG', dialCode: '+256', nameFa: 'اوگاندا', nameEn: 'Uganda' },
  { iso2: 'ET', dialCode: '+251', nameFa: 'اِتیوپی', nameEn: 'Ethiopia' },
  { iso2: 'EE', dialCode: '+372', nameFa: 'اِستونی', nameEn: 'Estonia' },
  { iso2: 'SK', dialCode: '+421', nameFa: 'اِسلُواکی', nameEn: 'Slovakia' },
  { iso2: 'EC', dialCode: '+593', nameFa: 'اکوادور', nameEn: 'Ecuador' },
  { iso2: 'US', dialCode: '+1', nameFa: 'ایالات متحده آمریکا', nameEn: 'United States' },
  { iso2: 'IT', dialCode: '+39', nameFa: 'ایتالیا', nameEn: 'Italy' },
  { iso2: 'IR', dialCode: '+98', nameFa: 'ایران', nameEn: 'Iran' },
  { iso2: 'IE', dialCode: '+353', nameFa: 'ایرلند', nameEn: 'Ireland' },
  { iso2: 'IS', dialCode: '+354', nameFa: 'ایسلند', nameEn: 'Iceland' },
  { iso2: 'BB', dialCode: '+1246', nameFa: 'باربادوس', nameEn: 'Barbados' },
  { iso2: 'BS', dialCode: '+1242', nameFa: 'باهاما', nameEn: 'Bahamas' },
  { iso2: 'BH', dialCode: '+973', nameFa: 'بحرین', nameEn: 'Bahrain' },
  { iso2: 'BR', dialCode: '+55', nameFa: 'برزیل', nameEn: 'Brazil' },
  { iso2: 'BM', dialCode: '+1441', nameFa: 'برمودا', nameEn: 'Bermuda' },
  { iso2: 'BN', dialCode: '+673', nameFa: 'برونئی', nameEn: 'Brunei' },
  { iso2: 'BY', dialCode: '+375', nameFa: 'بلاروس', nameEn: 'Belarus' },
  { iso2: 'BG', dialCode: '+359', nameFa: 'بلغارستان', nameEn: 'Bulgaria' },
  { iso2: 'BE', dialCode: '+32', nameFa: 'بلژیک', nameEn: 'Belgium' },
  { iso2: 'BZ', dialCode: '+501', nameFa: 'بلیز', nameEn: 'Belize' },
  { iso2: 'BD', dialCode: '+880', nameFa: 'بنگلادش', nameEn: 'Bangladesh' },
  { iso2: 'BJ', dialCode: '+229', nameFa: 'بنین', nameEn: 'Benin' },
  { iso2: 'BT', dialCode: '+975', nameFa: 'بوتان', nameEn: 'Bhutan' },
  { iso2: 'BW', dialCode: '+267', nameFa: 'بوتسوانا', nameEn: 'Botswana' },
  { iso2: 'BI', dialCode: '+257', nameFa: 'بوروندی', nameEn: 'Burundi' },
  { iso2: 'BF', dialCode: '+226', nameFa: 'بورکینافاسو', nameEn: 'Burkina Faso' },
  { iso2: 'BA', dialCode: '+387', nameFa: 'بوسنی و هرزگوین', nameEn: 'Bosnia and Herzegovina' },
  { iso2: 'BO', dialCode: '+591', nameFa: 'بولیوی', nameEn: 'Bolivia' },
  { iso2: 'TJ', dialCode: '+992', nameFa: 'تاجیکِستان', nameEn: 'Tajikistan' },
  { iso2: 'TZ', dialCode: '+255', nameFa: 'تانزانیا', nameEn: 'Tanzania' },
  { iso2: 'TH', dialCode: '+66', nameFa: 'تایلند', nameEn: 'Thailand' },
  { iso2: 'TW', dialCode: '+886', nameFa: 'تایوان', nameEn: 'Taiwan' },
  { iso2: 'TM', dialCode: '+993', nameFa: 'ترکمنستان', nameEn: 'Turkmenistan' },
  { iso2: 'TR', dialCode: '+90', nameFa: 'ترکیه', nameEn: 'Türkiye' },
  { iso2: 'TT', dialCode: '+1868', nameFa: 'ترینیداد و توباگو', nameEn: 'Trinidad and Tobago' },
  { iso2: 'TN', dialCode: '+216', nameFa: 'تونس', nameEn: 'Tunisia' },
  { iso2: 'TO', dialCode: '+676', nameFa: 'تونگا', nameEn: 'Tonga' },
  { iso2: 'TV', dialCode: '+688', nameFa: 'تووالو', nameEn: 'Tuvalu' },
  { iso2: 'TK', dialCode: '+690', nameFa: 'توکلائو', nameEn: 'Tokelau' },
  { iso2: 'TG', dialCode: '+228', nameFa: 'توگو', nameEn: 'Togo' },
  { iso2: 'TL', dialCode: '+670', nameFa: 'تیمور شرقی', nameEn: 'Timor-Leste' },
  { iso2: 'JM', dialCode: '+1876', nameFa: 'جامائیکا', nameEn: 'Jamaica' },
  { iso2: 'GI', dialCode: '+350', nameFa: 'جبل طارق', nameEn: 'Gibraltar' },
  { iso2: 'JE', dialCode: '+44', nameFa: 'جرزی', nameEn: 'Jersey' },
  { iso2: 'AX', dialCode: '+35818', nameFa: 'جزایر الند', nameEn: 'Åland Islands' },
  { iso2: 'TC', dialCode: '+1649', nameFa: 'جزایر تورکس و کایکوس', nameEn: 'Turks and Caicos Islands' },
  { iso2: 'GS', dialCode: '+500', nameFa: 'جزایر جورجیای جنوبی و ساندویچ جنوبی', nameEn: 'South Georgia' },
  { iso2: 'SB', dialCode: '+677', nameFa: 'جزایر سلیمان', nameEn: 'Solomon Islands' },
  { iso2: 'FO', dialCode: '+298', nameFa: 'جزایر فاروئه', nameEn: 'Faroe Islands' },
  { iso2: 'FK', dialCode: '+500', nameFa: 'جزایر فالکلند', nameEn: 'Falkland Islands' },
  { iso2: 'MH', dialCode: '+692', nameFa: 'جزایر مارشال', nameEn: 'Marshall Islands' },
  { iso2: 'MP', dialCode: '+1670', nameFa: 'جزایر ماریانای شمالی', nameEn: 'Northern Mariana Islands' },
  { iso2: 'VI', dialCode: '+1340', nameFa: 'جزایر ویرجین ایالات متحده آمریکا', nameEn: 'United States Virgin Islands' },
  { iso2: 'VG', dialCode: '+1284', nameFa: 'جزایر ویرجین بریتانیا', nameEn: 'British Virgin Islands' },
  { iso2: 'PN', dialCode: '+64', nameFa: 'جزایر پیت‌کرن', nameEn: 'Pitcairn Islands' },
  { iso2: 'BQ', dialCode: '+599', nameFa: 'جزایر کارائیب هلند', nameEn: 'Caribbean Netherlands' },
  { iso2: 'UM', dialCode: '+268', nameFa: 'جزایر کوچک حاشیه‌ای ایالات متحده آمریکا', nameEn: 'United States Minor Outlying Islands' },
  { iso2: 'CK', dialCode: '+682', nameFa: 'جزایر کوک', nameEn: 'Cook Islands' },
  { iso2: 'CC', dialCode: '+61', nameFa: 'جزایر کوکوس', nameEn: 'Cocos (Keeling) Islands' },
  { iso2: 'KY', dialCode: '+1345', nameFa: 'جزایر کیمن', nameEn: 'Cayman Islands' },
  { iso2: 'NF', dialCode: '+672', nameFa: 'جزیره نورفک', nameEn: 'Norfolk Island' },
  { iso2: 'BV', dialCode: '+47', nameFa: 'جزیرهٔ بووه', nameEn: 'Bouvet Island' },
  { iso2: 'IM', dialCode: '+44', nameFa: 'جزیرهٔ مَن', nameEn: 'Isle of Man' },
  { iso2: 'CX', dialCode: '+61', nameFa: 'جزیرهٔ کریسمس', nameEn: 'Christmas Island' },
  { iso2: 'AZ', dialCode: '+994', nameFa: 'جمهوری آذربایجان', nameEn: 'Azerbaijan' },
  { iso2: 'CF', dialCode: '+236', nameFa: 'جمهوری آفریقای مرکزی', nameEn: 'Central African Republic' },
  { iso2: 'DO', dialCode: '+1', nameFa: 'جمهوری دومینیکن', nameEn: 'Dominican Republic' },
  { iso2: 'CZ', dialCode: '+420', nameFa: 'جمهوری چک', nameEn: 'Czechia' },
  { iso2: 'CG', dialCode: '+242', nameFa: 'جمهوری کُنگو', nameEn: 'Congo' },
  { iso2: 'DJ', dialCode: '+253', nameFa: 'جیبوتی', nameEn: 'Djibouti' },
  { iso2: 'DK', dialCode: '+45', nameFa: 'دانمارک', nameEn: 'Denmark' },
  { iso2: 'CV', dialCode: '+238', nameFa: 'دماغهٔ سبز', nameEn: 'Cape Verde' },
  { iso2: 'DM', dialCode: '+1767', nameFa: 'دومینیکا', nameEn: 'Dominica' },
  { iso2: 'RE', dialCode: '+262', nameFa: 'رئونیون', nameEn: 'Réunion' },
  { iso2: 'RW', dialCode: '+250', nameFa: 'رواندا', nameEn: 'Rwanda' },
  { iso2: 'RU', dialCode: '+7', nameFa: 'روسیه', nameEn: 'Russia' },
  { iso2: 'RO', dialCode: '+40', nameFa: 'رومانی', nameEn: 'Romania' },
  { iso2: 'ZM', dialCode: '+260', nameFa: 'زامبیا', nameEn: 'Zambia' },
  { iso2: 'ZW', dialCode: '+263', nameFa: 'زیمبابوه', nameEn: 'Zimbabwe' },
  { iso2: 'ST', dialCode: '+239', nameFa: 'سائوتومه و پرنسیپ', nameEn: 'São Tomé and Príncipe' },
  { iso2: 'CI', dialCode: '+225', nameFa: 'ساحل عاج', nameEn: 'Ivory Coast' },
  { iso2: 'WS', dialCode: '+685', nameFa: 'ساموآ', nameEn: 'Samoa' },
  { iso2: 'AS', dialCode: '+1684', nameFa: 'ساموآی آمریکا', nameEn: 'American Samoa' },
  { iso2: 'SM', dialCode: '+378', nameFa: 'سان مارینو', nameEn: 'San Marino' },
  { iso2: 'TF', dialCode: '+262', nameFa: 'سرزمین‌های جنوبی و جنوبگانی فرانسه', nameEn: 'French Southern and Antarctic Lands' },
  { iso2: 'LK', dialCode: '+94', nameFa: 'سری‌لانکا', nameEn: 'Sri Lanka' },
  { iso2: 'BL', dialCode: '+590', nameFa: 'سن بارتلمی', nameEn: 'Saint Barthélemy' },
  { iso2: 'MF', dialCode: '+590', nameFa: 'سن مارتن', nameEn: 'Saint Martin' },
  { iso2: 'SX', dialCode: '+1721', nameFa: 'سن مارتن', nameEn: 'Sint Maarten' },
  { iso2: 'PM', dialCode: '+508', nameFa: 'سن-پیِر و میکلُن', nameEn: 'Saint Pierre and Miquelon' },
  { iso2: 'LC', dialCode: '+1758', nameFa: 'سنت لوسیا', nameEn: 'Saint Lucia' },
  { iso2: 'SH', dialCode: '+2', nameFa: 'سنت هلن', nameEn: 'Saint Helena, Ascension and Tristan da Cunha' },
  { iso2: 'VC', dialCode: '+1784', nameFa: 'سنت وینسنت و گرنادین‌ها', nameEn: 'Saint Vincent and the Grenadines' },
  { iso2: 'KN', dialCode: '+1869', nameFa: 'سنت کیتس و نویس', nameEn: 'Saint Kitts and Nevis' },
  { iso2: 'SN', dialCode: '+221', nameFa: 'سنگال', nameEn: 'Senegal' },
  { iso2: 'SG', dialCode: '+65', nameFa: 'سنگاپور', nameEn: 'Singapore' },
  { iso2: 'SE', dialCode: '+46', nameFa: 'سوئد', nameEn: 'Sweden' },
  { iso2: 'CH', dialCode: '+41', nameFa: 'سوئیس', nameEn: 'Switzerland' },
  { iso2: 'SJ', dialCode: '+4779', nameFa: 'سوالبارد و یان ماین', nameEn: 'Svalbard and Jan Mayen' },
  { iso2: 'SD', dialCode: '+249', nameFa: 'سودان', nameEn: 'Sudan' },
  { iso2: 'SS', dialCode: '+211', nameFa: 'سودان جنوبی', nameEn: 'South Sudan' },
  { iso2: 'SR', dialCode: '+597', nameFa: 'سورینام', nameEn: 'Suriname' },
  { iso2: 'SY', dialCode: '+963', nameFa: 'سوریه', nameEn: 'Syria' },
  { iso2: 'SO', dialCode: '+252', nameFa: 'سومالی', nameEn: 'Somalia' },
  { iso2: 'SL', dialCode: '+232', nameFa: 'سیرالئون', nameEn: 'Sierra Leone' },
  { iso2: 'SC', dialCode: '+248', nameFa: 'سیشل', nameEn: 'Seychelles' },
  { iso2: 'CL', dialCode: '+56', nameFa: 'شیلی', nameEn: 'Chile' },
  { iso2: 'EH', dialCode: '+2', nameFa: 'صحرای غربی', nameEn: 'Western Sahara' },
  { iso2: 'RS', dialCode: '+381', nameFa: 'صربستان', nameEn: 'Serbia' },
  { iso2: 'IQ', dialCode: '+964', nameFa: 'عراق', nameEn: 'Iraq' },
  { iso2: 'SA', dialCode: '+966', nameFa: 'عربستان سعودی', nameEn: 'Saudi Arabia' },
  { iso2: 'OM', dialCode: '+968', nameFa: 'عمان', nameEn: 'Oman' },
  { iso2: 'GH', dialCode: '+233', nameFa: 'غنا', nameEn: 'Ghana' },
  { iso2: 'FR', dialCode: '+33', nameFa: 'فرانسه', nameEn: 'France' },
  { iso2: 'IL', dialCode: '+972', nameFa: 'فلسطين اشغالی', nameEn: 'Israel' },
  { iso2: 'PS', dialCode: '+970', nameFa: 'فلسطین', nameEn: 'Palestine' },
  { iso2: 'FI', dialCode: '+358', nameFa: 'فنلاند', nameEn: 'Finland' },
  { iso2: 'FJ', dialCode: '+679', nameFa: 'فیجی', nameEn: 'Fiji' },
  { iso2: 'PH', dialCode: '+63', nameFa: 'فیلیپین', nameEn: 'Philippines' },
  { iso2: 'KG', dialCode: '+996', nameFa: 'قرقیزستان', nameEn: 'Kyrgyzstan' },
  { iso2: 'KZ', dialCode: '+7', nameFa: 'قزاقستان', nameEn: 'Kazakhstan' },
  { iso2: 'QA', dialCode: '+974', nameFa: 'قطر', nameEn: 'Qatar' },
  { iso2: 'IO', dialCode: '+246', nameFa: 'قلمرو بریتانیا در اقیانوس هند', nameEn: 'British Indian Ocean Territory' },
  { iso2: 'CY', dialCode: '+357', nameFa: 'قِبرِس', nameEn: 'Cyprus' },
  { iso2: 'LA', dialCode: '+856', nameFa: 'لائوس', nameEn: 'Laos' },
  { iso2: 'LB', dialCode: '+961', nameFa: 'لبنان', nameEn: 'Lebanon' },
  { iso2: 'LV', dialCode: '+371', nameFa: 'لتونی', nameEn: 'Latvia' },
  { iso2: 'LS', dialCode: '+266', nameFa: 'لسوتو', nameEn: 'Lesotho' },
  { iso2: 'PL', dialCode: '+48', nameFa: 'لهستان', nameEn: 'Poland' },
  { iso2: 'LU', dialCode: '+352', nameFa: 'لوکزامبورگ', nameEn: 'Luxembourg' },
  { iso2: 'LR', dialCode: '+231', nameFa: 'لیبـِریا', nameEn: 'Liberia' },
  { iso2: 'LY', dialCode: '+218', nameFa: 'لیبی', nameEn: 'Libya' },
  { iso2: 'LT', dialCode: '+370', nameFa: 'لیتوانیایی‌ها', nameEn: 'Lithuania' },
  { iso2: 'LI', dialCode: '+423', nameFa: 'لیختن‌اشتاین', nameEn: 'Liechtenstein' },
  { iso2: 'MG', dialCode: '+261', nameFa: 'ماداگاسکار', nameEn: 'Madagascar' },
  { iso2: 'MQ', dialCode: '+596', nameFa: 'مارتینیک', nameEn: 'Martinique' },
  { iso2: 'MW', dialCode: '+265', nameFa: 'مالاوی', nameEn: 'Malawi' },
  { iso2: 'MT', dialCode: '+356', nameFa: 'مالت', nameEn: 'Malta' },
  { iso2: 'MV', dialCode: '+960', nameFa: 'مالدیو', nameEn: 'Maldives' },
  { iso2: 'MY', dialCode: '+60', nameFa: 'مالزی', nameEn: 'Malaysia' },
  { iso2: 'ML', dialCode: '+223', nameFa: 'مالی', nameEn: 'Mali' },
  { iso2: 'MO', dialCode: '+853', nameFa: 'ماکائو', nameEn: 'Macau' },
  { iso2: 'YT', dialCode: '+262', nameFa: 'مایوت', nameEn: 'Mayotte' },
  { iso2: 'HU', dialCode: '+36', nameFa: 'مجارستان', nameEn: 'Hungary' },
  { iso2: 'MA', dialCode: '+212', nameFa: 'مراکش', nameEn: 'Morocco' },
  { iso2: 'EG', dialCode: '+20', nameFa: 'مصر', nameEn: 'Egypt' },
  { iso2: 'MN', dialCode: '+976', nameFa: 'مغولستان', nameEn: 'Mongolia' },
  { iso2: 'MK', dialCode: '+389', nameFa: 'مقدونیه شمالی', nameEn: 'North Macedonia' },
  { iso2: 'MR', dialCode: '+222', nameFa: 'موریتانی', nameEn: 'Mauritania' },
  { iso2: 'MU', dialCode: '+230', nameFa: 'موریس', nameEn: 'Mauritius' },
  { iso2: 'MZ', dialCode: '+258', nameFa: 'موزامبیک', nameEn: 'Mozambique' },
  { iso2: 'MD', dialCode: '+373', nameFa: 'مولداوی', nameEn: 'Moldova' },
  { iso2: 'MC', dialCode: '+377', nameFa: 'موناکو', nameEn: 'Monaco' },
  { iso2: 'MS', dialCode: '+1664', nameFa: 'مونتسرات', nameEn: 'Montserrat' },
  { iso2: 'ME', dialCode: '+382', nameFa: 'مونته‌نگرو', nameEn: 'Montenegro' },
  { iso2: 'MX', dialCode: '+52', nameFa: 'مکزیک', nameEn: 'Mexico' },
  { iso2: 'MM', dialCode: '+95', nameFa: 'میانمار', nameEn: 'Myanmar' },
  { iso2: 'FM', dialCode: '+691', nameFa: 'میکرونزی', nameEn: 'Micronesia' },
  { iso2: 'NR', dialCode: '+674', nameFa: 'نائورو', nameEn: 'Nauru' },
  { iso2: 'NA', dialCode: '+264', nameFa: 'نامیبیا', nameEn: 'Namibia' },
  { iso2: 'NO', dialCode: '+47', nameFa: 'نروژ', nameEn: 'Norway' },
  { iso2: 'NP', dialCode: '+977', nameFa: 'نپال', nameEn: 'Nepal' },
  { iso2: 'NE', dialCode: '+227', nameFa: 'نیجر', nameEn: 'Niger' },
  { iso2: 'NG', dialCode: '+234', nameFa: 'نیجریه', nameEn: 'Nigeria' },
  { iso2: 'NZ', dialCode: '+64', nameFa: 'نیوزیلند', nameEn: 'New Zealand' },
  { iso2: 'NU', dialCode: '+683', nameFa: 'نیووی', nameEn: 'Niue' },
  { iso2: 'NI', dialCode: '+505', nameFa: 'نیکاراگوئه', nameEn: 'Nicaragua' },
  { iso2: 'HT', dialCode: '+509', nameFa: 'هائیتی', nameEn: 'Haiti' },
  { iso2: 'NL', dialCode: '+31', nameFa: 'هلند', nameEn: 'Netherlands' },
  { iso2: 'IN', dialCode: '+91', nameFa: 'هند', nameEn: 'India' },
  { iso2: 'HN', dialCode: '+504', nameFa: 'هُندوراس', nameEn: 'Honduras' },
  { iso2: 'HK', dialCode: '+852', nameFa: 'هُنگ کُنگ', nameEn: 'Hong Kong' },
  { iso2: 'VA', dialCode: '+3', nameFa: 'واتیکان', nameEn: 'Vatican City' },
  { iso2: 'WF', dialCode: '+681', nameFa: 'والیس و فوتونا', nameEn: 'Wallis and Futuna' },
  { iso2: 'VU', dialCode: '+678', nameFa: 'وانواتو', nameEn: 'Vanuatu' },
  { iso2: 'VE', dialCode: '+58', nameFa: 'ونزوئلا', nameEn: 'Venezuela' },
  { iso2: 'VN', dialCode: '+84', nameFa: 'ویتنام', nameEn: 'Vietnam' },
  { iso2: 'PY', dialCode: '+595', nameFa: 'پاراگوئه', nameEn: 'Paraguay' },
  { iso2: 'PW', dialCode: '+680', nameFa: 'پالائو', nameEn: 'Palau' },
  { iso2: 'PA', dialCode: '+507', nameFa: 'پاناما', nameEn: 'Panama' },
  { iso2: 'GN', dialCode: '+224', nameFa: 'پاپوآ گینه نو', nameEn: 'Guinea' },
  { iso2: 'PG', dialCode: '+675', nameFa: 'پاپوآ گینه نو', nameEn: 'Papua New Guinea' },
  { iso2: 'PK', dialCode: '+92', nameFa: 'پاکستان', nameEn: 'Pakistan' },
  { iso2: 'PT', dialCode: '+351', nameFa: 'پرتغال', nameEn: 'Portugal' },
  { iso2: 'PE', dialCode: '+51', nameFa: 'پرو', nameEn: 'Peru' },
  { iso2: 'PR', dialCode: '+1', nameFa: 'پورتوریکو', nameEn: 'Puerto Rico' },
  { iso2: 'PF', dialCode: '+689', nameFa: 'پُلی‌نِزی فرانسه', nameEn: 'French Polynesia' },
  { iso2: 'TD', dialCode: '+235', nameFa: 'چاد', nameEn: 'Chad' },
  { iso2: 'CN', dialCode: '+86', nameFa: 'چین', nameEn: 'China' },
  { iso2: 'JP', dialCode: '+81', nameFa: 'ژاپن', nameEn: 'Japan' },
  { iso2: 'CR', dialCode: '+506', nameFa: 'کاستاریکا', nameEn: 'Costa Rica' },
  { iso2: 'NC', dialCode: '+687', nameFa: 'کالدونیای جدید', nameEn: 'New Caledonia' },
  { iso2: 'KH', dialCode: '+855', nameFa: 'کامبوج', nameEn: 'Cambodia' },
  { iso2: 'CM', dialCode: '+237', nameFa: 'کامِرون', nameEn: 'Cameroon' },
  { iso2: 'CA', dialCode: '+1', nameFa: 'کانادا', nameEn: 'Canada' },
  { iso2: 'KR', dialCode: '+82', nameFa: 'کرهٔ جنوبی', nameEn: 'South Korea' },
  { iso2: 'HR', dialCode: '+385', nameFa: 'کرُواسی', nameEn: 'Croatia' },
  { iso2: 'CO', dialCode: '+57', nameFa: 'کلمبیا', nameEn: 'Colombia' },
  { iso2: 'CD', dialCode: '+243', nameFa: 'کنگو دموکراتیک', nameEn: 'DR Congo' },
  { iso2: 'KE', dialCode: '+254', nameFa: 'کنیا', nameEn: 'Kenya' },
  { iso2: 'CU', dialCode: '+53', nameFa: 'کوبا', nameEn: 'Cuba' },
  { iso2: 'CW', dialCode: '+599', nameFa: 'کوراسائو', nameEn: 'Curaçao' },
  { iso2: 'XK', dialCode: '+383', nameFa: 'کوزوو', nameEn: 'Kosovo' },
  { iso2: 'KP', dialCode: '+850', nameFa: 'کُره شمالی', nameEn: 'North Korea' },
  { iso2: 'KW', dialCode: '+965', nameFa: 'کُویت', nameEn: 'Kuwait' },
  { iso2: 'KI', dialCode: '+686', nameFa: 'کیریباتی', nameEn: 'Kiribati' },
  { iso2: 'GA', dialCode: '+241', nameFa: 'گابن', nameEn: 'Gabon' },
  { iso2: 'GM', dialCode: '+220', nameFa: 'گامبیا', nameEn: 'Gambia' },
  { iso2: 'GE', dialCode: '+995', nameFa: 'گرجستان', nameEn: 'Georgia' },
  { iso2: 'GD', dialCode: '+1473', nameFa: 'گرنادا', nameEn: 'Grenada' },
  { iso2: 'GG', dialCode: '+44', nameFa: 'گرنزی', nameEn: 'Guernsey' },
  { iso2: 'GL', dialCode: '+299', nameFa: 'گرینلند', nameEn: 'Greenland' },
  { iso2: 'GU', dialCode: '+1671', nameFa: 'گوآم', nameEn: 'Guam' },
  { iso2: 'GT', dialCode: '+502', nameFa: 'گواتِمالا', nameEn: 'Guatemala' },
  { iso2: 'GP', dialCode: '+590', nameFa: 'گوادلوپ', nameEn: 'Guadeloupe' },
  { iso2: 'GY', dialCode: '+592', nameFa: 'گویان', nameEn: 'Guyana' },
  { iso2: 'GF', dialCode: '+594', nameFa: 'گویان فرانسه', nameEn: 'French Guiana' },
  { iso2: 'GQ', dialCode: '+240', nameFa: 'گینه استوایی', nameEn: 'Equatorial Guinea' },
  { iso2: 'GW', dialCode: '+245', nameFa: 'گینه بیسائو', nameEn: 'Guinea-Bissau' },
  { iso2: 'YE', dialCode: '+967', nameFa: 'یمن', nameEn: 'Yemen' },
  { iso2: 'GR', dialCode: '+30', nameFa: 'یونان', nameEn: 'Greece' },
]

export const defaultCountry: Country =
  countries.find((c) => c.iso2 === 'OM') ?? countries[0]

/** Unicode regional-indicator flag, derived from the ISO alpha-2 code — no per-country asset needed. */
export function flagEmoji(iso2: string): string {
  return String.fromCodePoint(
    ...[...iso2.toUpperCase()].map((c) => 127397 + c.charCodeAt(0)),
  )
}
